token:
  expiration_time: 864000000
  secret: '{cipher}AYAyPGc6ddFJdLDJMFD+o7MuP3rRtaO5jjBJZe/nXDEIH0FFv+48DPgd94qrEq9ypFrzRhWFYv4sdefFeYThK0BwYPmS2A03CtJ10Yxkh6LLztZI1Yr797X5oKJDX8SJiNk3xBngmh+YQlHwpFJ9/ZeHNPGckWg2yyMHa0bnNMrRnV6/UjCdUKiY7ANLjU3UemopakcEIFxN71/7lec3EuNNMQ8WhqzB+kPdpfEShBafJ+1xPXnDobPqISI8ldp5cTFGmGXXLhjPLGbEHH/Kh/nZFJpgSbqmmBDZwsb79GHRfkQDsNPaehU+SUm3y7oui3EkFUodkl3xIBcJzh8ddtbXyHyTe8EUTWugkD+3a2fmN95Kib1yx1ETZkbd83wBlqRjJtGMrFyTbQ+EyVFBrbcGmIq3rWPgS+ZCAy6y571YIL81H97iOSRNNAHBzx7Pp7azLKlm3dFqj4/7bWOerWQDc1LJiXHNkzHwbUYLadVKc/vSPfnacAviQysRnQgkWag+eFYxb7aE/xvSbUnUVbAcmiWQEYVMl/uBKfXju5fxlqUs6OyuLRxn5tpOVwYaQHOmhDxAWhoPY7xL4xuyuamaodePXBEGJjrSRsvc5qpuYHPxMX6EGZImD2sCLTQsKzX7xTU9yCZpxzPvYcennCa1S005f3C5tLrgXI53mm3vixRBCeDOQCUc1957eFXUsLWlVOflyzmGM9L2tcOW+b0XGTmGLcrcDIJ0RzGPlpEJwPf/pkYr+uI7A0bX0gN8kbn4OSg/oFPRGY0N9KayudMei31xF1M0h3RteSmdCfeQdDGXO0Jk/W2wlXqTyAO16YzEmbZ3zMJP9kwKK4XLtHdplXF0V+63ocjkUSgS72y/mYvA3EEze2me5hYgQiWAASk='

gateway:
  ip: 192.168.2.19

spring: 
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:testdb
    username: sa
    password: '{cipher}AYAus8m1ibtqf5JLp2ETZehQJZBKDkxBSeZZ3QVXwra56ySeaueax2hY3GzV6nXvPsxjzLtEkndQEvhwGGR5z9blHAhUT419OUSfs3NqY93cO3+z+XFnsrZSYwbBX5tO0rovrBOBFR97bbgt80PCil62VDhtd2NE6Y8oAhPWDDF5I4EHg3Z1y4FLMGGPlPASkJCG9jmqKud2AqqpaT0pcJnf08cDFhtB9v5eF+gOGyrMKKn5pD6pd9ahCKaFUwtI7LnPC4UE0tSs3mh/6/2ib7QmVnVkgvavg1w5/U9LreWg2qXj4+/rLOsbnWR2JgowukWrdxGyW7ch42DtpN2c8ZVdGw4xFSKXz3/i1XIs6tC0DwaDEekN6576cfetcUmqYYh6ChkFNaK8gFa+JVYegujM0APxkPgu/k6U/GwzApgItxBuOFWZZM/lDx4JjaIeuxW7gUDaLfZbdnsFvuOmLSNewEWmDu70lpP3BYsDSKRZy1pbH2ams5uWF5Km83BuufBb4e1Zd47t2MU6O9K1ttsyxV2mi8wbZns5qfL2NH5bzA=='
    generate-unique-name: false
    name: testdb
