server:
  port: 8888
spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
#          uri: C:\Users\DIR-N-0153\Desktop\OJT\msa\git-local-repo
          uri: https://github.com/yn15/spring-cloud-repo.git